version: 1.0

database:
  url: //localhost:1521/xe
  poolSize: 5
  password: epod
  username: letownia
video:
  storageDirectory: output
  initialDelaySeconds: 5
  intervalMilliseconds: 1000
previewWindow:
  width: 500
  height: 400